---
title: "ObserverCombine"
---

# Purpose
This script combines various observer data into a single set-level dataset. 
```{r}
# Set up the environment
library(tidyverse, quietly = TRUE)
library(here)
```

```{r}
# Load the data
GearConfig <- readRDS(here("ModelBuild", "FisheryData", "Observer_GearConfig.rds"))
SetEnvir <- readRDS(here("ModelBuild", "FisheryData", "Observer_SetEnvir.rds"))
Trips <- readRDS(here("ModelBuild", "FisheryData", "Observer_Trips.rds"))
Catch <- readRDS(here("ModelBuild", "FisheryData", "Observer_Catch.rds"))
```

```{r}
# Rename common fields so they're all the same across tables
GearConfig <- GearConfig |>
  rename(TRIP_NUM = T_TRIP_NUM, SET_NUM = S_SET_NUM)

SetEnvir <- SetEnvir |>
  rename(TRIP_NUM = T_TRIP_NUM)

Catch <- Catch |>
  rename(TRIP_NUM = T_TRIP_NUM, SET_NUM = S_SET_NUM)
```

```{r}
# Combine the three detail tables into a single table
# Using a full join so that we retain all sets for now
GearSet <- full_join(SetEnvir, GearConfig)
ObservedSetDetails_allSets <- full_join(GearSet, Trips)

# Combine with catch keeping only those trips and sets common to both tables
ObsCatch_withDetails_allSets <- inner_join(Catch, ObservedSetDetails_allSets, 
                                   by = c("TRIP_NUM", "SET_NUM"))

```

```{r}
# Filter out trips we don't want: 
# American Samoa (we want trips that start with "LL" not "AS")
# experimental trips (we want trips with no experimental trip code)
ObsCatch_Details_HIonly <- ObsCatch_withDetails_allSets |>
  filter(str_starts(TRIP_NUM, "LL") & is.na(EXPR_TRIP_TYPE_ID))
```

```{r}
# Save output in two different formats
saveRDS(object = ObsCatch_Details_HIonly, file = here("ModelBuild", "FisheryData", "ObsCatch_Details_HIonly.rds"))
write_csv(ObsCatch_Details_HIonly, file = here("ModelBuild", "FisheryData", "ObsCatch_Details_HIonly.csv"))
```

