project:
  type: book
  output-dir: docs
execute:
  cache: true
  freeze: auto
book:
  title: "Pelagic mizer model"
  subtitle: "An updated mizer model for Hawaiʻi-based longline fisheries"
  author: 
    - name: "Phoebe Woodworth-Jefcoats"
    - name: "Beth Lumsden"
    - name: "Joseph M. O'Malley"
  date: June 2026
  date-format: long
  license: "CC BY"
  sidebar:
    background: "#D9E3E4"
    search: true
    style: floating
    collapse-level: 1
    border: true
  repo-url: https://github.com/noaa-pifsc/Pelagic-mizer-model
  repo-actions: [edit, issue]
  page-footer: 
    border: false
    background: light
    left: | 
      &copy; CC-1.0
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
    
  chapters:
    - index.qmd
    - AboutFisheries.qmd
    - AboutData.qmd
    - SpeciesParams.qmd
    - FishingParams.qmd
    - CalVal.qmd
    - ImproveFit.qmd
    - RunningMizer.qmd
    - PossibleApps.qmd
    - references.qmd


bibliography: references.bib
csl: apa.csl

prefer-html: true
format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    toc: true
    toc-depth: 5
    theme: 
      light: 
        - cosmo